"use client";

import React, { useState, useEffect } from "react";
import { getLocalSeedState } from "@/lib/seedData";
import { Cpu, Activity, ShieldCheck, CheckCircle2 } from "lucide-react";

export default function AdminAnalysisPage() {
  const [analyses, setAnalyses] = useState<any[]>([]);

  useEffect(() => {
    const seed = getLocalSeedState();
    setAnalyses(seed.analyses);
  }, []);

  return (
    <div className="space-y-6">
      
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 bg-navy-800 border border-navy-700 rounded-3xl p-6 shadow-xl">
        <div>
          <h1 className="text-2xl font-bold text-white flex items-center gap-2">
            <Cpu className="w-6 h-6 text-purple-400" />
            <span>AI Inference Analysis Log</span>
          </h1>
          <p className="text-xs text-gray-400 mt-1">
            Detailed frame-by-frame person detection statistics generated by the YOLO object detection model.
          </p>
        </div>
      </div>

      {/* Analysis Cards Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {analyses.map((item, idx) => (
          <div key={idx} className="bg-navy-800 border border-navy-700 rounded-3xl p-6 shadow-xl space-y-4">
            
            {/* Header */}
            <div className="flex items-start justify-between border-b border-navy-700/60 pb-3">
              <div>
                <span className="text-[10px] font-extrabold uppercase tracking-wider text-purple-400 bg-purple-500/10 border border-purple-500/20 px-2 py-0.5 rounded-md">
                  {item.modelName || "YOLOv8n"} ({item.modelVersion || "v8.2"})
                </span>
                <h3 className="font-bold text-white text-base mt-1">
                  {item.cameraName || `Camera 0${idx + 1}`}
                </h3>
                <p className="text-xs text-gray-400">Location: Karur New Bus Stand</p>
              </div>

              <span className={`px-3 py-1 rounded-full text-xs font-extrabold border ${
                item.activityLevel === "HIGH"
                  ? "bg-emerald-500/20 text-emerald-400 border-emerald-500/30"
                  : item.activityLevel === "MEDIUM"
                  ? "bg-amber-500/20 text-amber-400 border-amber-500/30"
                  : "bg-gray-500/20 text-gray-400 border-gray-500/30"
              }`}>
                {item.activityLevel}
              </span>
            </div>

            {/* Statistics Display */}
            <div className="grid grid-cols-3 gap-2 bg-navy-900/90 p-3.5 rounded-2xl text-center border border-navy-700">
              <div>
                <span className="text-[10px] text-gray-400 uppercase font-semibold block">Average</span>
                <span className="text-xl font-extrabold text-emerald-400">{item.averagePersonCount}</span>
                <span className="text-[9px] text-gray-500 block">people</span>
              </div>
              <div>
                <span className="text-[10px] text-gray-400 uppercase font-semibold block">Maximum</span>
                <span className="text-xl font-extrabold text-blue-400">{item.maximumPersonCount}</span>
                <span className="text-[9px] text-gray-500 block">people</span>
              </div>
              <div>
                <span className="text-[10px] text-gray-400 uppercase font-semibold block">Minimum</span>
                <span className="text-xl font-extrabold text-gray-300">{item.minimumPersonCount}</span>
                <span className="text-[9px] text-gray-500 block">people</span>
              </div>
            </div>

            {/* Metadata Footer */}
            <div className="pt-2 text-xs text-gray-400 space-y-1">
              <div className="flex justify-between">
                <span>Total Frames Sampled:</span>
                <span className="font-semibold text-white">{item.totalFramesAnalyzed || 3600}</span>
              </div>
              <div className="flex justify-between">
                <span>Analysis Timestamp:</span>
                <span className="font-mono text-[11px] text-gray-300">
                  {new Date(item.analyzedAt).toLocaleString()}
                </span>
              </div>
            </div>

          </div>
        ))}
      </div>

    </div>
  );
}
